### PR TITLE
Fix problem with HomePageLogoUri when deploying STS project as Virtua…

### PR DESCRIPTION
**Pull request by tancevsasa**
…l Application on IIS

### CODE REVIEW

**Comment by skoruba** [comment]
Btw: what about favicon? :-) Is it same issue?

**Comment by tancevsasa** [comment]
> Btw: what about favicon? :-) Is it same issue?

Correct. That part of code has been fixed now too, internally tested and everything is as expected.
Code has been committed too 

image

@skoruba  I am not sure if I should close issue or you are?

**Comment by skoruba** [comment]
Can you please include this change for AdminUI as well?
https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin/Views/Shared/_Layout.cshtml#L11-L12
Thanks!

**Comment by tancevsasa** [comment]
> Can you please include this change for AdminUI as well?
> https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin/Views/Shared/_Layout.cshtml#L11-L12
> Thanks!

Sure, no problem.

**Comment by tancevsasa** [comment]
> > Can you please include this change for AdminUI as well?
> > https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin/Views/Shared/_Layout.cshtml#L11-L12
> > Thanks!
> 
> Sure, no problem.

Done and code has been committed

**Comment by tancevsasa** [comment]
@skoruba Sorry for asking this but I am contributing for the first time and I would like to know what are next steps related to this pull requests.  If you can explain me in short or refer me to a some link I can read more.
I want to start my work on other improvements and before that I would like to finish this one I already started

**Comment by skoruba** [comment]
@tancevsasa - thank you for your message, I have to apologize that I didn't merge this PR, but I will do it asap. ;-)

**Comment by tancevsasa** [comment]
I suppose this PR will be merged in next couple of days?

**Comment by skoruba** [comment]
I would like to merge these changes into dev branch first, can you please check conflicts?
Thanks.

**Comment by tancevsasa** [comment]
> I would like to merge these changes into dev branch first, can you please check conflicts?

That has been done and tested. Thanks

**Comment by tancevsasa** [comment]
Hi, should I do something special in order to have this fix merged into DEV?
Please advise?

**Comment by skoruba** [comment]
Thank you for your changes and I am very sorry for long delay for merging this PR. 👍

**Pull request merged**
