### PR TITLE
Update to .Net Core 2.1.

### PR DESCRIPTION
**Pull request by skoruba**
Fix issues - #26 #27

### CODE REVIEW

**Comment by skoruba** [comment]
@xmichaelx - can you check it please?

**Comment by xmichaelx** [comment]
Works nicely 👍

**Comment by TomasHubelbauer** [comment]
@skoruba Are you okay with me squashing and merging approved PRs or would you prefer I defer to you doing the actual merge?

**Comment by skoruba** [comment]
@TomasHubelbauer You can absolutely - create squash and merge. Thanks 👍

**Comment by TomasHubelbauer** [comment]
I recommend you set the `dev` branch as protected on GitHub, because right now after merging a PR from `dev` to `master` it offers deleting the `dev` branch, which it should do only for feature branches, not `dev`.

**Comment by skoruba** [comment]
Great tip, It's done. Now is `dev` branch set as protected.

**Pull request merged**
