### PR TITLE
Moved the configuration to a common IdentityServer4.Shared project th…

### PR DESCRIPTION
**Pull request by ganmuru**
My intention here is to move all IdentityServer related functionality to STS project and consider Admin as just any other IS4 Client that is trying to access IdentityServer4 functionality.

I have merged the configuration that was common between Admin and STS. Moved them to a separate IdentityServer4.Shared folder. My end goal is for Admin Client to access IS4 functionality via the API present in STS project.

Please share your thoughts.

### CODE REVIEW

**Comment by ganmuru** [comment]
Can you please review the PR and share your thoughts

**Comment by skoruba** [comment]
I will review it. Thank you 👍🏼😊

**Comment by skoruba** [comment]
It is really complex PR. I understand your idea with exluding all configuration into separate project but I have used the another PR where we move all configuration into `appsettings.json` of each project. Can you please check dev branch with latest changes?

Thanks!

**Comment by skoruba** [comment]
I am closing this PR, because there are a lit of changes, it is not possible to merge.
Thanks

**Pull request closed without merging**
