### PR TITLE
Data Protection migrations for PostgreSql

### PR DESCRIPTION
**Pull request by inbarbarkai**
I've implemented the migrations of the data protection tables for PostgresSql

### CODE REVIEW

**Comment by inbarbarkai** [comment]
@skoruba I've ran the unit tests locally and they work. I have no idea why it's failing here.
Can you rerun it?

**Comment by skoruba** [comment]
Thanks for this PR, but I already did it - for PostgreSQL and Mysql as well. :-)

**Comment by inbarbarkai** [comment]
It's not on the dev branch.

**Comment by skoruba** [comment]
I merge it now.

**Pull request closed without merging**
