### PR TITLE
Update RedirectUris

### PR DESCRIPTION
**Pull request by Varorbc**

### CODE REVIEW

**Comment by skoruba** [comment]
Why do you change the uri? I think original uri is correct. Thanks

**Comment by Varorbc** [comment]
http 5000
https 5001

**Comment by skoruba** [comment]
Check what you changed in PR.

**Comment by Varorbc** [comment]
https://github.com/skoruba/IdentityServer4.Admin/blob/5cda5fd65095eb99563e82360bbdaaad49433b3a/src/Skoruba.IdentityServer4.STS.Identity/Properties/launchSettings.json#L24

**Pull request closed without merging**
