### PR TITLE
Add STS missing Chinese resources

### PR DESCRIPTION
**Pull request by Seaear**

### CODE REVIEW

**Comment by skoruba** [comment]
Great job @Seaear 👍 
I added some additional translations - [commit](https://github.com/skoruba/IdentityServer4.Admin/commit/c3e46459fa7ba0e612e78e956dbeeef5e7ef528e)
Can you please add these translations as well?
Thanks!

**Comment by Seaear** [comment]
@skoruba Already translated all

**Comment by skoruba** [comment]
@Seaear Great - I pushed one latest change in Register view, please check it.
Thanks!

**Comment by Seaear** [comment]
@skoruba Ok, already added

**Pull request merged**
