### PR TITLE
Extract UI project for use in existing setups (v2)

### PR DESCRIPTION
**Pull request by Brice-xCIT**
This PR enables consumers to use the UI with an existing IdentityServer4 environment, by letting arbitrary Startup code to inject the UI into an existing application's pipeline. This essentially solves issues #770, #409, #55, #322, #133 and maybe more.

`services.AddIdentityServer4AdminUI(...)`, `app.UseIdentityServer4AdminUI()` and `endpoints.MapIdentityServer4AdminUI()` are now exposed, with a wide range of configuration options that support both option binding to appsettings and programmatic configuration.

The UI is now provided as an area, which should allow it to be added to a single application alongside the STS. It should also be extensible since the project is a Razor Class Library. And of course using the UI in a standalone application is natural, as demonstrated by the Admin app.

### CODE REVIEW

**Comment by Brice-xCIT** [comment]
@skoruba This is it. Let me know if you see anything wrong!

**Comment by skoruba** [comment]
@Brice-xCIT - thanks for your PR, I will check it. 👍

**Comment by skoruba** [comment]
Hey @Brice-xCIT - I switched this PR to `release/2.0.0-beta-1` - but there are conflicts, could you please check it?
Thanks!

**Comment by Brice-xCIT** [comment]
Hi! Dang it, I seem to have branched out at the wrong place :( I will look into resolving the conflicts. 
However would you consider making a 1.x release out of this still? 2.0 seems to come with a mandatory upgrade to IS4 4.x, which itself comes with breaking changes.

**Comment by Brice-xCIT** [comment]
Conflicts are resolved for v2.x.

**Comment by skoruba** [comment]
@Brice-xCIT - thanks for your great work! I will check both version 👍

**Comment by skoruba** [comment]
I've tested this version and everything work really great, even I've tried overwrite some resource, view and it works perfectly! 
I will go througt the code and check all the details.
I am really impressed. 🚀❤

**Comment by Brice-xCIT** [comment]
I'm glad to hear it's working out well! :) I wouldn't be surprised if there were some minor hiccups there and there, or if the code could be further cleaned up or refactored.

**Comment by skoruba** [comment]
@Brice-xCIT - for sure, I will take a look at details. 👍 Do you think that similar thing we can do it with Admin.Api project in the future? Extract api controllers to separate package and reference it through the nuget package as well like UI?
Thanks!

**Comment by Brice-xCIT** [comment]
I think the same could be done without too many issues for the API - it is very symmetrically implemented. Maybe in the process some common types could be further extracted down to Admin.Shared. I won't have much time to work on the API in the coming months, though :/

**Comment by skoruba** [comment]
@Brice-xCIT - For sure, I will check it and make some appropriate changes. 👍

**Comment by jotatoledo** [comment]
is there any guide to use this feature? sorry for bumping this, I wasnt sure if opening a new issue just to ask this is right.

**Comment by skoruba** [comment]
@jotatoledo - Yep 😊 it is not documented yet. But in the branch called `release/2.0.0` is now available.

**Pull request merged**
