### PR TITLE
🚀 Release/2.1.0

### PR DESCRIPTION
**Pull request by skoruba**

### CODE REVIEW

**Comment by senzacionale** [comment]
Any progress on this topic? When new .net will be supported?

**Comment by skoruba** [comment]
It is almost ready, I am waiting for the final release of health-check packages. It will be ready after few days. 🙂

**Comment by senzacionale** [comment]
Great to hear. Thank you

**Comment by senzacionale** [comment]
Hi. Sorry to ask. Any new infos?

**Comment by skoruba** [comment]
Sorry for delay 😊 hopefully, it will be ready next week

**Pull request merged**
