### PR TITLE
add require email confirmation option

### PR DESCRIPTION
**Pull request by martinussuherman**
First of all sorry for all the trouble, I'm such a noob on git lol. As I've promised I create this PR again.

Regards, Martinus

### CODE REVIEW

**Comment by martinussuherman** [comment]
Seems this PR will require #632 to be applied first so the checks will succeed.

**Comment by skoruba** [comment]
Thanks for this PR 👍🏼

**Comment by martinussuherman** [comment]
> 
> 
> Thanks for this PR 👍🏼

You're welcome. Thank you for this project, which is great 😃 👍

**Comment by skoruba** [comment]
I merged your changes manually, thanks 👍

**Pull request closed without merging**
