### PR TITLE
Add API for AdminUI

### PR DESCRIPTION
**Pull request by skoruba**
#105 - first preview of new project `Skoruba.IdentityServer4.Admin.Api` which contains:
- list of API controllers - for managing of the IdentityServer4 and Asp.Net Core Identity
- Add swagger support

### CODE REVIEW

**Comment by ekjuanrejon** [comment]
@skoruba will these be merged any time soon and new packages be released?

**Comment by skoruba** [comment]
Sure, can you try this new API?

**Comment by ekjuanrejon** [comment]
Yes if you publish new nuget packages

**Comment by skoruba** [comment]
Yes, I will create new package ASAP.
Thanks.

**Pull request merged**
