### PR TITLE
IdentityServer4.Admin, Account/AccessDenied, configurable fav-icon

### PR DESCRIPTION
**Pull request by ViRuSTriNiTy**
see issue #552

### CODE REVIEW

**Comment by ViRuSTriNiTy** [comment]
> Thanks for your changes:
> 
> * why do you delete images?

They are not used anymore because favicon.ico is used now. Why keep the old files? 

> * is it possible to use _rootConfiguration directly in view - instead of ViewData?

Yes absolutely, i was unsure whether i should add this improvment as the Account controller already sets a viewdata parameter. I will provide another commit.

**Comment by ViRuSTriNiTy** [comment]
@skoruba I have fixed the CI build errors. Please have a look at the finished PR.

**Comment by ViRuSTriNiTy** [comment]
Any news on this?

**Comment by skoruba** [comment]
Thank you for these changes, I am very sorry for long delay. Currently I am working on new release and these changes are great. 👍

**Pull request merged**
