### PR TITLE
Localization persian(farsi) language

### PR DESCRIPTION
**Pull request by saeedrahmo**
this pull request add persian(farsi) language (fa) resources to admin and identity projects

### CODE REVIEW

**Comment by skoruba** [comment]
Great job @saeedrahmo - I will merge your changes into `dev` branch.

Can you please fix conflicting files?

Thank you :)

**Comment by skoruba** [comment]
Please, try to run tests :)

**Comment by skoruba** [comment]
@saeedrahmo - Can you please check latest changes on `dev` branch - we added new views/controllers for profile management etc. Can you add these additional translations as well? :)

Thank you for your great job 👍

**Comment by saeedrahmo** [comment]
> @saeedrahmo - Can you please check latest changes on `dev` branch - we added new views/controllers for profile management etc. Can you add these additional translations as well? :)
> 
> Thank you for your great job 👍

**Comment by saeedrahmo** [comment]
i fixed problems and i will do add new translations for dev branch

**Comment by skoruba** [comment]
@saeedrahmo - can you please check missing translations for https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.STS.Identity/Resources/Views/Shared/_Layout.fa.resx
According the https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.STS.Identity/Resources/Views/Shared/_ScopeListItem.en.resx

Thank you.

**Comment by saeedrahmo** [comment]
yes i will check

**Comment by skoruba** [comment]
Maybe you can try to check latest dev branch - run in browser and check the views and missing translations. :) Thank you

**Comment by skoruba** [comment]
@saeedrahmo - can you please add these translations? :)
It will help for us to finish this beta version.
Thank you 👍 

>https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.STS.Identity/Resources/Views/Shared/_Layout.fa.resx
> According the https://github.com/skoruba/IdentityServer4.Admin/blob/dev/src/Skoruba.IdentityServer4.STS.Identity/Resources/Views/Shared/_Layout.en.resx

**Comment by saeedrahmo** [comment]
im woriking on it

**Pull request merged**
