### PR TITLE
correcting git auth by adding callback-path

### PR DESCRIPTION
**Pull request by messaddek**
When trying to configure github authentication, i figured out that the callbackpath setting is missing.

Regards

### CODE REVIEW

**Comment by skoruba** [comment]
Hey @messaddek - can you please make this change against branch called `release/2.0.0` - it would be perfect!
Thanks.

**Comment by messaddek** [comment]
Hey @skoruba I will perform this today.

Thank you

**Comment by messaddek** [comment]
> Hey @messaddek - can you please make this change against branch called `release/2.0.0` - it would be perfect!
> Thanks.

it has been already done

**Comment by skoruba** [comment]
I can see some conflicts here in PR after switching to release/2.0.0, can you check it please? 😊
Thanks!

**Comment by messaddek** [comment]
Done, could you please check the release/2.0.0

**Comment by messaddek** [comment]
Pr closed, a new one has been created for release/2.0.0

**Pull request closed without merging**
