### PR TITLE
Update to .NET 6

### PR DESCRIPTION
**Pull request by JonasBRasmussen**
- Updates the target framework to net6.0
- Updates Dockerfiles to use .NET 6 base images
- Updates all NuGet dependencies (includes dependency cleanup and unit test fixes)
- Makes use of Directory.Build.props files to simplify project files
- Updates template builder

### CODE REVIEW

**Comment by JonasBRasmussen** [comment]
@skoruba The AppVeyor build fails because the image used does not contain the .NET 6 SDK. Can you update as described in https://www.appveyor.com/blog/2021/11/10/visual-studio-2022-image?

**Comment by JonasBRasmussen** [comment]
@skoruba Any chance of getting the AppVeyor build agent upgraded so this can be merged?

**Comment by skoruba** [comment]
Sure, I will, but I have had a time yet. :-) I am sorry for delay

**Comment by JonasBRasmussen** [comment]
No worries. 😊 I'll just stay on the fork until then.

**Review by skoruba — APPROVED** [review]
Great work, thank you for your work on this! 😊

**Pull request merged**
