### PR TITLE
Features/theming

### PR DESCRIPTION
**Pull request by ioxFR**
Hi,

i purpose new feature, ability to switch between some themes from settings defined in appsettings.json.
This will be implemented for admin and sts UI.

Themes implemented are visible here:
https://bootswatch.com/

I would like to integrate all of this themes and keep the current one as default if the appsettings.json value is empty.
Otherwise it will apply the mentionned theme if it exist.

If you got some other ideas/suggest...

- [x]  Integration of bootswatch themes
- [x]  Integration of new configuration value for theme
- [x]  System to apply theme configured
- [x]  Apply same stuff for Admin project
- [x]  Documentation
- [x]  Testing

Enjoy!

### CODE REVIEW

**Comment by skoruba** [comment]
This is cool 👍🏼

**Comment by skoruba** [comment]
@ioxFR - could you please resolve the conflicts which were made after merging the CSP feature? 👍 
Thanks!

**Comment by ioxFR** [comment]
@skoruba done :)

**Comment by skoruba** [comment]
Thanks for you PR, I merged this into feature branch, because it is necesarry to polish it. I noticed that some items are not correctly re-designed after application of any theme and menu on the top is visible incorrectly. I will fix it, they are minnor fixes, you did great work, thanks. 👍

**Pull request merged**
