### PR TITLE
Improved signout in external providers

### PR DESCRIPTION
**Pull request by zinkpad**
- FIXED: Added [AllowAnonymous] to Logout action (this is the redirect URI after logout in external provider, keep in mind that first you are logged out in your local identity server).
- Added a custom SignInManager: you need keep the issued "id_token" for signout later in external provider. (See ExternalController: https://github.com/IdentityServer/IdentityServer4/blob/main/samples/Quickstarts/3_AspNetCoreAndApis/src/IdentityServer/Quickstart/Account/ExternalController.cs).

You can try this pull request by adding the "Demo Identity Server" in your StartupHelper:

```
authenticationBuilder.AddOpenIdConnect("oidc", "OpenID Connect", options =>
            {
                options.SignInScheme = IdentityConstants.ExternalScheme;
                options.SignOutScheme = IdentityServerConstants.SignoutScheme;

                options.Authority = "https://demo.identityserver.io/";
                options.ClientId = "interactive.public";
                options.ResponseType = "code";
                options.UsePkce = true;
                options.TokenValidationParameters = new TokenValidationParameters
                {
                    NameClaimType = "name",
                    RoleClaimType = "role"
                };
                options.SaveTokens = true;
                options.Events.OnRedirectToIdentityProviderForSignOut = async options =>
                {
                    options.ProtocolMessage.IdTokenHint = await options.HttpContext.GetTokenAsync("id_token");
                };
            });
```

### CODE REVIEW

**Comment by skoruba** [comment]
Thank you for your PR 👍🏼
I will test it, maybe I would like to use same approach in the implementation like in IS4 sample - in controller, not create custom SignInManager, but I will check the details around that and definitely thanks for your fix 😊

**Comment by zinkpad** [comment]
Ok, I thought the same as you but I think it's hard work ... if you don't want to use the SignInManager class (AccountController in QuickStart.UI doesn't use it) you have to change a lot of things in your AccountController (user provisioning, registration, two factor auth, etc.).

Anyway, you probably have more experience working with IS4 than me... I'll be stay tunned.

**Comment by skoruba** [comment]
You are right, I will check it - thank you for your clarification for your implementation. 👍

**Review by skoruba — APPROVED** [review]

**Comment by skoruba** [comment]
Thanks for your PR. 👍

**Comment by zinkpad** [comment]
Hi @skoruba,

I detected two issues dealing wih external providers:

1. When you login on an external provider and you have two factor authentication enabled, the id_token is lost due twofactor auth remove the external cookie before invoke SignInWithClaimsAsync mehod. I think I fixed this issue using ExternalCookieAuthenticationScheme and overriding the GetExternalLoginInfoAsync method in CustomSignInManager to use these scheme. I tested it and works like a charm.

2. If you disable local login in your client and have enabled two factor auth (and only one external provider), when you enter the auth code you are redirected again to login page, and then to external provider and then asking for two factor code again. I think the login page is required and not auto redirect the user to external provider.

I'm working on this issues, I hope send you a pull request soon.

**Comment by skoruba** [comment]
Thanks 👍

**Comment by skoruba** [comment]
@zinkpad - did you find any way how to find the issues which you mentioned above? I would love to use your changes in next RC4.
Thanks 👍

**Comment by zinkpad** [comment]
Yes, you can check my last commits on my fork repository:

https://github.com/zinkpad/IdentityServer4.Admin/commits/improve-external-providers

But I think I have to revert the commit : https://github.com/zinkpad/IdentityServer4.Admin/commit/a6871333b71c0c580ae7e7ae7decdace2ce20ece because these changes are not needed.

The key to resolve these issues is to use the ExternalCookieAuthenticationScheme and remove multifactor authentication claim to prevent signin issues with external providers.

**Comment by skoruba** [comment]
Can you please send a PR with your changes? It would be the best. 😊
Thanks for your job!

**Comment by zinkpad** [comment]
FYI, CustomSignInManager class is based on source code at: https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Core/src/SignInManager.cs you can check it.

My environment consists in:

- A custom Skoruba.STS.Identity server with these improvements: 
  - Support for Oracle (also with serilog support).
  - Auto user registration and claims sync issued by our external provider.
  - Configured our custom Identity Server as external provider. 
  - [...]

- Our company Identity Server with support for:
   - Intranet login support.
   - Azure AD 
   - Windows auth
   - Cl@ve

**Comment by zinkpad** [comment]
> Can you please send a PR with your changes? It would be the best. 
> Thanks for your job!

Sure!...I just send you a pull request, please test it.

**Pull request merged**
