### PR TITLE
CSP Configuration Trusted Domains from appsettings.json

### PR DESCRIPTION
**Pull request by ioxFR**
Hi all,

For people who using Docker images from dockerhub to create app instance, you probably got an issue if you want to customise favicon or logo caused by CSP.
To fix this issue i created configuration in appsettings.json to configure a list of "approved" domains who contains some ressources like logo, favicon or other stuff for future versions.

- Configuration Added in appsettings.json, list or uri
- Added CSP middleware with configuration for default, image, font, script
- Changed class of img element for logo to use responsive class for image "img-fluid"

In progress:

- [x]  Integration of CSP Configuration in admin project

- [x]  Integration of gravatar domain as trusted by default

- [x] Fix for inline css & script

Related to #209 

Enjoy

### CODE REVIEW

**Comment by skoruba** [comment]
Hey, thanks for your PR, I think similar settings will be necessary to add into Admin project as well, could you please add this configuration there?
Thank!

**Comment by ioxFR** [comment]
Hi @skoruba 

Yes of course, i will do it by end of day.
Question for you, as gravatar is used for profile image currently it's required to add gravatar domain in configuration otherwise gravatar will be blocked by CSP.
Should i add gravatar domain directly from the code as trusted ?
In my opinion i think it's better.

**Comment by skoruba** [comment]
Maybe we can add gravatar into configuration like deafult value?
Thanks.

**Comment by ioxFR** [comment]
@skoruba ok, i added in to appsettings.json array, i will do it for admin side.
Let's see how it works.

**Comment by ioxFR** [comment]
@skoruba PR Ready for review.
As we discussed i implemented same stuff in admin in place of already existing csp rules.
Configuration from appsettings and google's fonts uri mentionned in appsettings array for admin, in the sts side the gravatar uri.

Enjoy!

**Comment by skoruba** [comment]
Thank you for this great PR. I have to test it. From the quick review I noticed that you removed UnSafeInline scripts from Admin UI, but I think that will broke the toastr notification which generates inline scripts into page.

**Comment by ioxFR** [comment]
hi @skoruba ,

I confim, it's right.
I don't know why during my first tests it was ok but after few more tests infact i get csp problem on inline stuff.
I will fix it tomorrow to integrate inline script & css.

**Comment by skoruba** [comment]
@ioxFR thank you 👍

**Comment by ioxFR** [comment]
@skoruba Done.
I added only in admin project unsafe inline on style and script and unsafeeval also for script.
In STS side i added missing style source csp config.

**Comment by skoruba** [comment]
@ioxFR - thank you for your great job 👍 - I will test it.

**Review by skoruba — APPROVED** [review]

**Pull request merged**
