### PR TITLE
docker support

### PR DESCRIPTION
**Pull request by ChrisSzabo**
- Added support for building docker containers for Admin, Api, and STS projects. Based off of code from @rherlt (https://github.com/skoruba/IdentityServer4.Admin/pull/325). 

- This version is a little more efficient when building the images because the newer VS docker tooling generated dockerfile code that also copies project references (.csproj files) when creating the dependency cache layers.

To run:
docker-compose up --build

To stop:
docker-compose down

Api Url: http://127.0.0.1.xip.io:5000/swagger/index.html
IdentityServer Admin: http://127.0.0.1.xip.io:9000
IdentityServer : http://127.0.0.1.xip.io

### CODE REVIEW

**Comment by bravecobra** [comment]
Any progress on this?

**Comment by skoruba** [comment]
Can you test this PR, please? I need help with this PR to migrate to net core 3.0. Can you help with this? Thanks

**Comment by bravecobra** [comment]
@skoruba sure. I already gave #325 a go and that seemed to be working for me at the time, of course lacking the Admin.Api. I'll try this one as well. Looking at the changes, there won't be too much of a difference except for the obvious Admin.API addition.

**Comment by bravecobra** [comment]
I found only 2 minor configuration issues.

The default seed of the db did not add the proper allowed redirect URI for Swagger to work. Swagger is running at http://127.0.0.1.xip.io:5000 so it should be allowed to be redirected to that endpoint,  Once I added that manually, like the screenshot below, it worked. Adding an entry (conditionally) to the seed will solve that.
image

Secondly the IdentityServerUri configuration for the API is incorrect in the `docker-compose.yml` file
That should be 
```
skoruba.identityserver4.admin.api:
    environment:
          - "AdminApiConfiguration:IdentityServerBaseUrl=http://127.0.0.1.xip.io"
```
And not the URI of the API service itself at port 5000. The parameter describes where you should authenticate, not where the API service is running.

Once 2 things were properly configured, everything seemed to work, including 2FA and API calls.

**Comment by bravecobra** [comment]
@skoruba as you mentioned .NET Core 3 support, the dockerfiles will require a little update to use the proper build images. So either you merge #390 first and update this PR or vice versa. Your choice. 
Those lines to be changed should then be resp.  `FROM mcr.microsoft.com/dotnet/core/sdk:3.0-buster AS builder` and `FROM mcr.microsoft.com/dotnet/core/aspnet:3.0-buster-slim`. I expect that to work.

Here is a reference for building .NET Core 3.0 Docker images with Github Actions: https://hjerpbakk.com/blog/2019/10/09/asp-net-core-docker-and-github-actions

**Comment by bravecobra** [comment]
As for reference, to get a running version `IdentityServer4.Admin` with SQL Server using `docker compose`, is now as easy as 

```powershell
docker-compose build
docker-compose up
```
We might want to add that to the documentation somewhere.

For people using ReSharper, add the `**/ReSharper.Caches/` folders to the `.dockerignore`.  `docker-compose` does not seem to be happy with them, but that's a minor issue and only for some.

**Comment by skoruba** [comment]
You are awesome @bravecobra - thanks for your feedback - can you send a PR with your changes?

**Comment by bravecobra** [comment]
@skoruba that would result in yet another PR for this. I can add one, but I'm sure @ChrisSzabo is willing to add these few minor adjustments. I'll make the changes in my fork based on his branch but I suggest we give him a bit of time to add them in. I'll submit an PR otherwise.

**Comment by bravecobra** [comment]
I tried to resolve the merge conflicts as well, but it seems there were "a lot" of configuration changes.  @skoruba is that something you want to fix or should I attempt to fix that as well? That shouldn't be too hard, but it will result in changes in the `docker-compose.yml` as well since those values need to be overridden as environment variables.

**Comment by skoruba** [comment]
For sure @bravecobra - I will merge this PR. Can you resolve conflicts on this PR @ChrisSzabo and if you have time - it would be perfect - add the suggestions from @bravecobra. Thanks guys  for your great work.
I am sorry for delay on docker stuff in general, but finally I resolved some issue with docker on my computer yesterday, so now I am able to work with docker as well and verify all things from PR. 😊👍🏼
I really appreciate your help on this, because for me is new area. Thanks.

**Comment by bravecobra** [comment]
@skoruba will you be merging the .NET Core 3.0 branch to dev first, as that would affect this branch a b bit as well?

**Comment by skoruba** [comment]
For sure.

**Comment by skoruba** [comment]
@bravecobra - Done, merged on dev. :-)

**Comment by bravecobra** [comment]
I took a stab at fixing those merge conflicts, and it seems you already added the `IdentityRequireHttpsMetadata` property as `RequireHttpsMetadata`. Further the Serilog sink will require an extra ENV override for the connection string.
Also the seeding works a bit differently, so my fix on my branch doesn't work anymore as the property is now read from `appsettings.json`. So the conflict merging require a bit more work, but I should have something cooked up later today.

**Comment by bravecobra** [comment]
> @bravecobra - Done, merged on dev. :-)

Cool, tnx. I'll work that in as well.

**Comment by skoruba** [comment]
Perfect, thanks a lot. 👍

**Comment by bravecobra** [comment]
@skoruba I fixed the merge conflicts in #395 and merged in the latest dev branch adding extra .NET 3.0 support.

**Pull request merged**
