### PR TITLE
Multitenant support #101

### PR DESCRIPTION
**Pull request by mperk**

### CODE REVIEW

**Comment by skoruba** [comment]
Hi, thanks for your PR, could you please verify this PR against dev branch?
Thanks

**Comment by mperk** [comment]
> Hi, thanks for your PR, could you please verify this PR against dev branch?
> Thanks

Hey @skoruba , I'm happy to see you :) I have a few question but I didn't reach you. So I may have done something wrong, can you check the pr carefully. I tested on my local, it's work.

**Comment by skoruba** [comment]
I would like to test it, but take a look at conflicts there.😊

**Comment by mperk** [comment]
> I would like to test it, but take a look at conflicts there.😊

I did. It is a huge conflict 😊

**Comment by skoruba** [comment]
Hi @mperk - the multi-tenant support is currently out of scope of this project - so I am closing this PR.
Thank you for your effort on this PR - I really appreciate your work, maybe in the future I will take a look at this code and I will use it.

**Pull request closed without merging**
