### PR TITLE
 Support for single quote in PickerTag labels.

### PR DESCRIPTION
**Pull request by nlz242**
Currently, if an apostrophe is used in a label of the PickerTag, it generates invalid html.
It is invalid because the generated div has a data-bind attribute which has it's value inside single-quotes. This is obviously done because the value contains JSON, thus it has many double-quotes and should not be encased in double-quotes.

Fix escapes characters, like the single quote.
Useful for french, which has apostrophe in words.
For example : "The item" becomes "L'item"

### CODE REVIEW

**Comment by Aegide** [comment]
I'm working on the french translation and i was very worried about apostrophes with string extrapolation (or some other unseen mechanic that would break because of apostrophes).

Thanks !

**Comment by skoruba** [comment]
OK, I see. Did you try to put some item with single quote into DB as well - because I remember that I escape the single quote in JS side as well.

Thanks!

**Comment by skoruba** [comment]
Like this one: https://github.com/skoruba/IdentityServer4.Admin/blob/master/src/Skoruba.IdentityServer4.Admin/Scripts/App/components/Picker.js#L137

**Comment by skoruba** [comment]
BTW: For which field do you want to put text with single quote? Because I think that names of scopes, claims etc. are better without any quotes, but maybe I missed something. 😊

**Comment by Aegide** [comment]
I was worried that some values would "break" if an odd amount of apostrophes was used.
- `Please confirm your account by &lt;a href='{0}'&gt;clicking here&lt;/a&gt;.`
- `User with ID '{0}' asked for their personal data.`

Some values contains `'{0}'` or `{0}`, and it made me ask myself if there was some hidden functionnality that i was missing and could break.
 
**AuthenticatorVerified ( 0 => 1 )**
 - Your authenticator app has been verified.
 - Votre application d'**authentification a été vérifiée.**
 (/!\\)

**SuccessDisabled2FA ( 0 => 2 )**
- User with ID {0} has disabled 2fa.
- L'**utilisateur avec l**'ID {0} a désactivé 2fa. 
(/?\\)


**ErrorLoadingExternalLogin ( 0 => 3 )**
- Unexpected error occurred loading external login info for user with ID {0}.
- Une erreur inattendue s'**est produite lors du chargement des informations de connexion externe de l**'utilisateur avec l'**ID {0}.**
 (/!\\)


 **ErrorSettingEmail ( 0 => 4 )**
- Unexpected error occurred setting email for user with ID {0}.
- Une erreur inattendue s'**est produite lors du paramétrage de l**'**e-mail pour l**'utilisateur avec l'ID {0}.  
(/?\\)

_I tried to make it as clear as possible._

**Comment by nlz242** [comment]
For the commit associated to this pull request, it fixes the label under the pickerbox. 
image

In french, "click on the item to select" could be translated to "clicker sur l'item pour le sélectionner".
In that case, the apostrophe ends the data-bind attribute's value, thus leading to invalid html.

**Comment by skoruba** [comment]
Oh, now I see, what you meant, this is absolutely correct, thanks! 👍
I will test it.

**Comment by skoruba** [comment]
> I was worried that some values would "break" if an odd amount of apostrophes was used.
> 
> * `Please confirm your account by &lt;a href='{0}'&gt;clicking here&lt;/a&gt;.`
> * `User with ID '{0}' asked for their personal data.`
> 
> Some values contains `'{0}'` or `{0}`, and it made me ask myself if there was some hidden functionnality that i was missing and could break.
> 
> **AuthenticatorVerified ( 0 => 1 )**
> 
> * Your authenticator app has been verified.
> * Votre application d'**authentification a été vérifiée.**
>   (/!\)
> 
> **SuccessDisabled2FA ( 0 => 2 )**
> 
> * User with ID {0} has disabled 2fa.
> * L'**utilisateur avec l**'ID {0} a désactivé 2fa.
>   (/?\)
> 
> **ErrorLoadingExternalLogin ( 0 => 3 )**
> 
> * Unexpected error occurred loading external login info for user with ID {0}.
> * Une erreur inattendue s'**est produite lors du chargement des informations de connexion externe de l**'utilisateur avec l'**ID {0}.**
>   (/!\)
> 
> **ErrorSettingEmail ( 0 => 4 )**
> 
> * Unexpected error occurred setting email for user with ID {0}.
> * Une erreur inattendue s'**est produite lors du paramétrage de l**'**e-mail pour l**'utilisateur avec l'ID {0}.
>   (/?\)
> 
> _I tried to make it as clear as possible._

Did you test it, is it issue there? 😊

**Comment by Aegide** [comment]
> Did you test it, is it issue there? 

I did not test it yet, i was just worried about this possibility.
But thanks to this PR i feel better about that possibility.

**Comment by nlz242** [comment]
@Aegide If it can reassure you, so far this is the only issue i've ran into while implementing french.
I was gonna share our french translation (started doing it on and off, 2 weeks ago), but it is a bit janky. I'm a software guy, not a linguist eh! So i'll probably end up upgrading to yours once you share it :)

**Pull request merged**
