### PR TITLE
Initial upgrade for .NET Core 3.0 and CORS

### PR DESCRIPTION
**Pull request by sabitertan**
This PR includes minimum upgrade path explained by [Migrate from ASP.NET Core 2.2 to 3.0](https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-2.2&tabs=visual-studio).
It also includes nuget package upgrades to the latest previews.

### CODE REVIEW

**Comment by skoruba** [comment]
Nice, this is cool 👍😊 I look forward to .NET Core 3.0.
Thanks!

**Comment by sabitertan** [comment]
I updated Fluent Assertions in this PR but seems like tests needs to be updated :/

**Comment by skoruba** [comment]
Yes, I know, I have older version of FluentValidation in UnitTests because I will need to rewrite probable a lot of tests, so upgrading of this library will be later. :)

**Comment by skoruba** [comment]
I will continue here: #390.
Thanks for initial version!

**Pull request closed without merging**
