### PR TITLE
Russian localization improved slightly

### PR DESCRIPTION
**Pull request by pavel-usachev**
Hi,

I tried to make least changes as possible, but I'd rather not translate OAuth (OIDC) teminology. Reading this is really confusing. Fixed email confirmation message. It didn't show link to confirm user email if it sent in russian locale.

Also, I've changed images path to be considered as virtual directory not just a string, because `UsePathBaseMiddleware` doesn't affect these image pathes. That is an issue when it comes to URL-rewrite proxy.

### CODE REVIEW

**Comment by pavel-usachev** [comment]
I find out that some changes I made already done. Will you merge #561?

**Comment by skoruba** [comment]
Can you please check the coflicts? I've changed the destination branch to dev.
Thanks

**Comment by skoruba** [comment]
> 
> 
> I find out that some changes I made already done. Will you merge #561?

I've merged this, thanks for review.

**Comment by pavel-usachev** [comment]
> Can you please check the coflicts?

Done.

**Comment by skoruba** [comment]
Thank you 👍🏼

**Pull request merged**
