### PR TITLE
Add Docker support

### PR DESCRIPTION
**Pull request by Seaear**
1. Add "127.0.0.1 id.example.com" to hosts file.
2. In the directory where docker-compose.yml, Use the command "docker-compose build" build images, and use "docker-compose up" start services.

### CODE REVIEW

**Comment by skoruba** [comment]
@Seaear - Please take a look at latest dev branch - I've added setup for HTTPS only - the urls was changed.
Thanks.

**Comment by Seaear** [comment]
@skoruba HTTPS only  can be used as an option. In Docker, the reverse proxy  is used in the front (such as: nginx, caddy), and HTPPS is set in the reverse proxy.

**Comment by Seaear** [comment]
@skoruba I tested that HTTPS only is not affected in Docker.

**Comment by skoruba** [comment]
@Seaear - Sorry, I had to change back to http on localhost because we had some issues on linux.
Could you please revert your changes as well?
Thank you!

**Comment by Seaear** [comment]
Ok

**Comment by skoruba** [comment]
Thank you for this PR, I will process it later, because I need figure out more about docker and how to integrate and setup.

**Comment by Jaben** [comment]
@skoruba Do you want to do project docker builds and publish to hub?

With this PR (which looks great, @Seaear) -- it will require people to creating own images. In my case, we have CI (TeamCity) with Linux agents, and private docker repo -- this isn't a big deal. But others may not be able to get up and running quickly without built images ready to go.

If you add docker to your CI (Azure?) -- then you can publish both Identity and Admin UI docker images and save people that step.

**Comment by skoruba** [comment]
@Jaben - can you help me with this? I have no experience with docker. :)
Thanks!

**Comment by Jaben** [comment]
@skoruba I'll try. :)

I have limited experience with Azure Pipelines -- but it supports docker builds: https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/docker?view=azure-devops&tabs=yaml

Is the build file (yml) in the repo?

**Comment by skoruba** [comment]
I use the build configuration in Azure Piples, no yml file. :)

What do you suggest to getting started?

**Comment by TomasHubelbauer** [comment]
@skoruba We can switch from using the graphical UI to the YAML file, I'll be glad to help with that.

**Comment by edisonbrito** [comment]
> 1. Add "127.0.0.1 id.example.com" to hosts file.
> 2. In the directory where docker-compose.yml, Use the command "docker-compose build" build images, and use "docker-compose up" start services.

Hi, I'm trying to run docker-compose, but it looks like it can not run the bank update with SEED, you know what I could do?

**Comment by edisonbrito** [comment]
> > 1. Add "127.0.0.1 id.example.com" to hosts file.
> > 2. In the directory where docker-compose.yml, Use the command "docker-compose build" build images, and use "docker-compose up" start services.
> 
> Hi, I'm trying to run docker-compose, but it looks like it can not run the database update with SEED, you know what I could do?

ERROR THIS: System.InvalidOperationException: IDX20803: Unable to obtain configuration from: '[PII is hidden]'.

**Comment by skoruba** [comment]
Please, try restart STS app.

**Comment by mistereechapman** [comment]
Would the intention be that this project is reliant on an external db source to always be already setup? With a few small changes on this PR we could bring in a sql image also and inject in the connection string and make it alot more portable. Happy to help if interested.

**Comment by skoruba** [comment]
Of course, please send a PR with your suggestions. Thanks.

**Comment by christophla** [comment]
We are planning on deploying this into Kubernetes. I'd love to provide a helm chart based off of this PR.

**Comment by Danni-Ke** [comment]
Hi, I am new to both docker and IdentityServer4. I follow the instruction above. But my skoruba-Identityserver4 -admin always terminates like that.....
image
After I run the command, docker-compost up, it just gives me output like that.
image

**Comment by rherlt** [comment]
Hi,

since @Seaear does not seem to be active since a while, I used his code and resolved the conflicts. Please check this PR #325

**Comment by skoruba** [comment]
@Seaear - Thanks for this PR, I am sorry, that I didn't merge this PR earlier, but I have some trouble with docker at all. We will continue with docker support in PR - #367.

**Pull request closed without merging**
